steps:
  - command: make test

  - command: echo "should run after tests"; sleep 10; echo "completed"

  - command: echo "should run immediately"

  - input: 🚀 Deploy this build...
    fields:
      - select: Select a server
        key: deployment-target
        default: staging
        options:
          - value: staging
            label: staging
          - value: production
            label: production

  - command: echo "please deploy like NOW"
