env:
  - REGEN_CACHE:true

steps:
  - if: 'build.env("REGEN_CACHE") == "true"'
    label: "Do REGEN_CACHE"
    command: 'echo "REGEN_CACHE"'
  - if: 'build.env("REGEN_CACHE") == "false"'
    label: "Do not REGEN_CACHE"
    command: 'echo NO "REGEN_CACHE"'
  - command: "echo done"
