steps:
  - command: make test
    id: tests

  - command: echo "should run after tests"; sleep 10; echo "completed"
    id: dependent
    depends_on: tests

  - command: echo "should run immediately"
    id: independent

  - block: 🚀 Deploy this build...
    id: blocker
    fields:
      - select: Select a server
        key: deployment-target
        default: staging
        options:
          - value: staging
            label: staging
          - value: production
            label: production

  - command: .buildkite/trigger-deploy
    id: deploy-trigger
