steps:
  - command: make test

  - command: echo "should run after tests"; sleep 10; echo "completed"

  - command: echo "should run immediately"

  - input: 🚀 Deploy this build...
    id: blocker
    fields:
      - select: Select a server
        key: deployment-target
        default: staging
        options:
          - value: staging
            label: staging
          - value: production
            label: production

  - wait:
    if: build.message =~ /dont block/

  - command: echo "please deploy like NOW"
    id: deploy-trigger
