steps:
  - if: build.env("REGEN_CACHE") == "true"
    label: "this worked"
    command: 'echo "this worked"'
  - if: build.env("REGEN_CACHE") == "false"
    label: "shoud not work"
    command: "echo should not work"
  - command: "echo done"
