# steps:
#   - label: "One :golang:"
#     commands: make test

#   - wait

#   - label: set meta data
#     command: buildkite-agent meta-data set "REPO_NAME" "bar"

#   - wait

#   - label: shell meta
#     env:
#       REPO_NAME: "NO REPO_NAME"
#     commands:
#       - ./.buildkite/script.sh
#       - 'echo $$REPO_NAME'

#   - wait

#   - label: perisited env
#     commands:
#       - 'echo $$REPO_NAME'

steps:
  - label: "test"
    commands: make test
  - wait
  - label: perisited env
    commands:
      - "echo done"
